sequenceDiagram
    participant Customer
    participant BileMoApi@{ "type": "boundary" }
    Customer->>+BileMoApi:  Add a user
    alt The form isn't valid
        BileMoApi--xCustomer: Send a message with error
    else
          BileMoApi--xCustomer: Send a message to confirm the addition of user
    end
  